// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whzmoncahckaouqcjkyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indoem1vbmNhaGNrYW91cWNqa3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDE2NTUsImV4cCI6MjA3MTYxNzY1NX0.qPwl5dLeVTM8qjngozUGX8MUtT3G7UICatr5AzHXnUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});